export const RPC: { [networkId: string]: string } = {
  "1": "https://rpc.ankr.com/eth",
  "56": "https://rpc.ankr.com/bsc",
  "250": "https://fantom-mainnet.public.blastapi.io",
  "42161": "https://arbitrum.meowrpc.com",
  "137": "https://polygon.meowrpc.com",
  "10": "https://optimism-mainnet.public.blastapi.io",
  "43114": "https://avalanche.public-rpc.com",
  "8453": "https://base.meowrpc.com",
  "59144": "https://rpc.linea.build",
  "5": "https://rpc.ankr.com/eth_goerli",
  "80001": "https://polygon-mumbai-bor.publicnode.com",
  "17000": "https://ethereum-holesky.publicnode.com",
  "534352": "https://1rpc.io/scroll",
  "5000": "https://1rpc.io/mantle",
  "421614": "https://public.stackup.sh/api/v1/node/arbitrum-sepolia",
  "34443": "https://mode.drpc.org",
  "11155111": "https://rpc2.sepolia.org",
};
